spring:
  application:
    name: dispatch-docker${service-suffix}
    desc: DevOps Dispatch Docker Service
    version: 4.0.0
    packageName: com.tencent.devops.dispatch.docker

server:
  port: 21938
