spring:
  application:
    name: artifactory${service-suffix}
    desc: DevOps Artifactory Service
    version: 4.0.0
    packageName: com.tencent.devops.artifactory

server:
  port: 21922

artifactory:
  realm: local
